name: CI for game-2048

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout
        uses: actions/checkout@v4
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/game-2048:${{ github.run_number }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/game-2048:${{ github.run_number }}
      # - name: Docker Setup Docker
      #   uses: docker/setup-docker-action@v4.3.0

      # - name: docker version
      #   run: docker --version
      
      # - name: Build the image
      #   run: docker build -t devesh77388/game-2048:${{github.run_number}} .

      # - name: Docker Login
      #   uses: docker/login-action@v3.4.0
      #   with:
      #    username: ${{secrets.DOCKER_USERNAME}}
    
      #    password: ${{secrets.DOCKER_PASSWORD}}

      # - name: push to hub
      #   run: docker push devesh77388/game-2048:${{github.run_number}}
    


